Inventory.Web/Controllers/BillTypesController.cs
using Inventory.Repository.BillTypeService;
using Inventory.ViewModel.Bill;
using Inventory.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Web.Controllers
{
    public class BillTypesController : Controller
    {
        private IBillTypeRepo _billTypeRepo;

        public BillTypesController(IBillTypeRepo billTypeRepo)
        {
            _billTypeRepo = billTypeRepo;
        }
        [HttpGet]
        //[TypeFilter(typeof(CultureFilter), Arguments = new object[] { "af-ZA" })]
        public IActionResult Index(int pageSize=10,int pageNumber=1)
        {
            var billTypes = _billTypeRepo.GetAll(pageNumber, pageSize);
            return View(billTypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
       
        public IActionResult Create(CreateBillTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
               _billTypeRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _billTypeRepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public IActionResult Edit(BillTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _billTypeRepo.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _billTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }
        


    }
}

Inventory.Web/Controllers/CustomerTypeController.cs
using Inventory.Repository.CustomerTypeService;
using Inventory.Repository.Paging;
using Inventory.ViewModel.Bill;
using Inventory.ViewModel.Customer;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Web.Controllers
{
    public class CustomerTypeController : Controller
    {
        private ICustomerTypeRepo _customerTypeRepo;

        public CustomerTypeController(ICustomerTypeRepo customerTypeRepo)
        {
            _customerTypeRepo = customerTypeRepo;
        }

     
        public IActionResult Index(int pageSize = 10, int pageNumber = 1,string? searching=null)
        {
            PagedResult<CustomerTypeListViewModel> customerTypes;
             customerTypes = _customerTypeRepo.GetAll(pageSize, pageNumber);
            if (!String.IsNullOrEmpty(searching))
            {
                customerTypes =  _customerTypeRepo.Search(searching, pageSize, pageNumber);
              
            }
            return View(customerTypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateCustomerTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _customerTypeRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _customerTypeRepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public IActionResult Edit(CustomerTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _customerTypeRepo.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _customerTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Inventory.Web/Controllers/SalesTypesController.cs
using Inventory.Repository.BillTypeService;
using Inventory.Repository.SalesTypeService;
using Inventory.ViewModel.Bill;
using Inventory.ViewModel.Sales;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Web.Controllers
{
    public class SalesTypesController : Controller
    {
        private ISalesTypeService _salesTypeRepo;

        public SalesTypesController(ISalesTypeService salesTypeRepo)
        {
            _salesTypeRepo = salesTypeRepo;
        }
        [HttpGet]
        public IActionResult Index(int pageSize = 10, int pageNumber = 1)
        {
            var salesTypes = _salesTypeRepo.GetAll(pageNumber, pageSize);
            return View(salesTypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateSalesTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _salesTypeRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _salesTypeRepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public IActionResult Edit(SalesTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _salesTypeRepo.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _salesTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }


    }
}

Inventory.Web/Controllers/VendorTypesController.cs
using Inventory.Repository.BillTypeService;
using Inventory.Repository.VendorTypeService;
using Inventory.ViewModel.Bill;
using Inventory.ViewModel.Vendor;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Web.Controllers
{
    public class VendorTypesController : Controller
    {
        private IVendorTypeRepo _vendorTypeRepo;

        public VendorTypesController(IVendorTypeRepo vendorTypeRepo)
        {
            _vendorTypeRepo = vendorTypeRepo;
        }
        [HttpGet]
        public IActionResult Index(int pageSize = 10, int pageNumber = 1)
        {
            var vendorTypes = _vendorTypeRepo.GetAll(pageNumber, pageSize);
            return View(vendorTypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateVendorTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _vendorTypeRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _vendorTypeRepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public IActionResult Edit(VendorTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _vendorTypeRepo.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _vendorTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Inventory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory.Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Left Sidebar -->
            <div class="col-md-3 bg-dark text-light">
                <div class="py-4 px-3">
                    <h3>Dashboard</h3>
                </div>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="CustomerType" class="nav-link active">
                            <i class="fas fa-home mr-2"></i>
                            Customer Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-user mr-2"></i>
                            Customer
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="SalesTypes">
                            <i class="fas fa-envelope mr-2"></i>
                            Sales Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Sales Order
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Shipment
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                           Invoice
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Payment Receive
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="VendorTypes">
                            <i class="fas fa-cog mr-2"></i>
                            Vendor Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Vendor
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="PurchaseTypes">
                            <i class="fas fa-cog mr-2"></i>
                            Purchase Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Purchase Order
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Bill
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Payment Voucher
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Product
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="ProductTypes">
                            <i class="fas fa-cog mr-2"></i>
                           Product Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                           Unit of Measure
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Currency
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Branch
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Warehouse
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                           Cash Bank
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="PaymentTypes">
                            <i class="fas fa-cog mr-2"></i>
                           Payment Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="ShipmentType">
                            <i class="fas fa-cog mr-2"></i>
                            Shipment Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="InvoiceTypes">
                            <i class="fas fa-cog mr-2"></i>
                            Invoice Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="BillTypes">
                            <i class="fas fa-cog mr-2"></i>
                            Bill Type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                           User
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                           Change Password
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Role
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cog mr-2"></i>
                            Change Role
                        </a>
                    </li>
                </ul>
            </div>


            <!-- Main Content -->
            <div class="col-md-9">
                <!-- Top Navigation -->
                <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Contact</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-user-circle"></i>
                                        John Doe
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="#">Profile</a>
                                        <a class="dropdown-item" href="#">Settings</a>
                                        <a class="dropdown-item" href="#">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

                <!-- Main Content Body -->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Inventory.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Inventory.Web/Views/Shared/_search.cshtml
<form>
    <input class="form-control" type="text" placeholder="search.." name="searching" />
    <input type="submit" value="search" />
</form>